### PR TITLE
Problem Number 27 [C] 

### LINKED ISSUE #23: Problem Number 27 [C]
#### This issue is about [Problem No] (link to the Hackerrank Euler Problem).

- [x] Issue Title is in form `Problem Number [Language]`.
- [x] Language is either of C,C++,Python (IMPORTANT)
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] I got AC for this problem on Hackerrank.
- [x] I have checked that my solution is passing on Problem (in case you make some changes).

### PR DESCRIPTION
**Pull request by prateekiiest**
Fixes #23 
- [x] Pull Request Title is of form `Problem Number [Language]`.
- [x] This solution is prepared by me and not copied from anywhere else on the web.
- [x] I have added a __BY:{Your Hackerrank username} copyright comment__ in my solution.
- [x] I have updated index.md file (In appropriate folder in the appropriate manner).
- [x] I understand that pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by prateekiiest** [comment]
@sirjan13  reviews pls

**Comment by sirjan13** [comment]
Isnt your solution accepted by Hackerrank?

**Comment by prateekiiest** [comment]
Yes its accepted.

**Comment by prateekiiest** [comment]
I have given the link in the index.md file.

**Comment by sirjan13** [comment]
Just change the title of the PR according to the guidelines specified so as to mantain uniformity in the Pull Requests and check the checkbox for AC solution and then its good to be merged.Looking Forward for the changes 🙂

**Comment by prateekiiest** [comment]
Done @sirjan13

**Comment by sirjan13** [comment]
Great Job

**Pull request merged**
