### PR TITLE
Problem 035 [python]

### LINKED ISSUE #24: 035[python]
#### This issue is about [Problem No] (link to the Hackerrank Euler Problem).

- [x] Issue Title is in form `Problem Number [Language]`.
- [x] Language is either of C,C++,Python (IMPORTANT)
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] I got AC for this problem on Hackerrank.
- [x] I have checked that my solution is passing on Problem (in case you make some changes).
- [x] Assign this issue to me (I want to work on this).
- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

### PR DESCRIPTION
**Pull request by ReimuA**
Fixes #24 
- [x] Pull Request Title is of form `Problem Number [Language]`.
- [x] This solution is prepared by me and not copied from anywhere else on the web.
- [x] I have added a __BY:{Your Hackerrank username} copyright comment__ in my solution.
- [x] I have updated index.md file (In appropriate folder in the appropriate manner).
- [x] I understand that pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by vaibhav29498** [comment]
Please provide a link to your Hackerrank solution on the index.md page.

**Comment by ReimuA** [comment]
Fixed the link.

**Comment by vaibhav29498** [comment]
Thanks for contributing!

**Comment by vaibhav29498** [comment]
Thanks for contributing!

**Pull request merged**
